version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo # The PostgreSQL default database (automatically created at first launch)
    ports:
      - '5432:5432'
    volumes: 
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      #- db:/var/lib/postgresql/data

#volumes:
#  db:
#    driver: local